# Generated by Django 5.2.3 on 2025-06-28 12:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя источника')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_source')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(unique=True, verbose_name='Цитата')),
                ('weight', models.IntegerField(default=1, verbose_name='Вес цитаты')),
                ('likes', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лайки')),
                ('dislikes', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дизлайки')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_set', to='main.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['likes'],
                'constraints': [models.UniqueConstraint(fields=('quote',), name='unique_post')],
            },
        ),
    ]
